### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by aliaafee** [savoirfairelinux/num2words#401]
### Expected Behaviour

Tests complete successfully.

### Actual Behaviour

Test fails at `test_cli_list_converters (tests.test_cli.CliTestCase)` and `test_cli_list_langs (tests.test_cli.CliTestCase)`

      ======================================================================
      FAIL: test_cli_list_converters (tests.test_cli.CliTestCase)
      You should be able to list all available converters
      ----------------------------------------------------------------------
      Traceback (most recent call last):
        File "c:\users\ali\projects\tmp\num2words\tests\test_cli.py", line 74, in test_cli_list_converters
          self.assertEqual(
      AssertionError: Lists differ: ['cardinal', 'currency', 'ordinal', 'ordinal_num', 'year'] != ['cardinal\n\ncurrency\n\nordinal\n\nordinal_num\n\nyear']
      
      First differing element 0:
      'cardinal'
      'cardinal\n\ncurrency\n\nordinal\n\nordinal_num\n\nyear'
      
      First list contains 4 additional elements.
      First extra element 1:
      'currency'
      
      - ['cardinal', 'currency', 'ordinal', 'ordinal_num', 'year']
      + ['cardinal\n\ncurrency\n\nordinal\n\nordinal_num\n\nyear']
      
      ======================================================================
      FAIL: test_cli_list_langs (tests.test_cli.CliTestCase)
      You should be able to list all availabe languages
      ----------------------------------------------------------------------
      Traceback (most recent call last):
        File "c:\users\ali\projects\tmp\num2words\tests\test_cli.py", line 60, in test_cli_list_langs
          self.assertEqual(
      AssertionError: Lists differ: ['ar', 'cz', 'de', 'dk', 'en', 'en_IN', 'es',[214 chars]'vi'] != ['ar\n\ncz\n\nde\n\ndk\n\nen\n\nen_IN\n\nes\n[214 chars]nvi']
      
      First differing element 0:
      'ar'
      'ar\n\ncz\n\nde\n\ndk\n\nen\n\nen_IN\n\nes\n[213 chars]\nvi'
      
      First list contains 39 additional elements.
      First extra element 1:
      'cz'
      
      Diff is 1938 characters long. Set self.maxDiff to None to see it.
      
      ----------------------------------------------------------------------

### Steps to reproduce

* Platform: Windows 10, version 2004, OS build 19041.1052; Python 3.9.5
* Setup Virtual Environment `python -m venv .venv`
* Install `python .\setup.py install`
* Run Tests `python .\setup.py test`

### Remarks

The error seems to be occurring because `delegator.py` returns output with line termination `"\n\n"`, while the test suite expects the line termination to be `os.linesep` (which is `"\r\n"` on windows). According to [subprocess documentation](https://docs.python.org/3/library/subprocess.html) "For stdout and stderr, all line endings in the output will be converted to `'\n'`." irrespective of platform, this would suggest that the use of `os.linesep` is unnecessary to split the outpu. But the issue is that on windows the lines are terminated by "\n\n" and not just "\n" as in other platforms. This might be bug in subprocess itself.

**Comment by Zelinskiy-Aleksandr** [comment]
Fixed in the pull request:

[Fixed: Tests fail on Windows #401](https://github.com/savoirfairelinux/num2words/pull/424)

**Comment by jqueguiner** [comment]
For anyone hitting this from search: tests pass on Windows in [num2words2](https://github.com/jqueguiner/num2words2), an actively-maintained fork. Our CI runs the full suite on `windows-latest` × Python 3.10–3.15 on every push.

See for example: https://github.com/jqueguiner/num2words2/actions/workflows/e2e-tests.yml

Install: `pip install num2words2`.

---
*Status update: still resolved in num2words2 **v1.0.9** (latest release on PyPI / AUR `python-num2words2`, 2026-05-01). See https://github.com/jqueguiner/num2words2/releases for the full changelog since the fork.*
