### ISSUE TITLE
Error in conversion using Italian language

### ISSUE THREAD

**Issue by RomoloPoliti-INAF** [savoirfairelinux/num2words#528]
the conversion of numbers in the Italian language works only with numbers (int, float) and not with str
### Expected Behaviour

>>> from num2words import num2words
>>> num2words(2001,lang='it')
'duemilauno'

### Actual Behaviour

>>> num2words('2001.1',lang='it')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/num2words/__init__.py", line 98, in num2words
    return getattr(converter, 'to_{}'.format(to))(number, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/num2words/lang_IT.py", line 155, in to_cardinal
    string = self.thousands_to_cardinal(number)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/num2words/lang_IT.py", line 107, in thousands_to_cardinal
    prefix = self.to_cardinal(thousands) + "mila"
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/num2words/lang_IT.py", line 149, in to_cardinal
    string = CARDINAL_WORDS[number]

**Comment by mrodriguezg1991** [comment]
Hello, 
The package version has been updated, and after testing what you describe above it seems to be working properly, however can you test on your end for validation?
Thanks and hope is fixed

```
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from num2words import num2words
>>> num2words(2001,lang='it')
'duemilauno'
>>> num2words(2001.1,lang='it')
'duemilauno virgola uno'
>>> 
```

**Comment by RomoloPoliti-INAF** [comment]
I appreciate your support.
I tested it from my side, and it works properly.

Thanks
