### ISSUE TITLE
When specifying hundreds, the logic for the Armenian language breaks

### ISSUE THREAD

**Issue by xdownedx** [savoirfairelinux/num2words#599]
### Expected Behaviour

return something in the supported language: "am"

### Actual Behaviour

`Traceback (most recent call last):
  File "/Users/xdownedx/docxGENERATE/docxGen/app.py", line 6, in <module>
    print(num2words(amount, lang='am'))
  File "/Users/xdownedx/docxGENERATE/docxGen/.venv/lib/python3.10/site-packages/num2words/__init__.py", line 104, in num2words
    return getattr(converter, 'to_{}'.format(to))(number, **kwargs)
  File "/Users/xdownedx/docxGENERATE/docxGen/.venv/lib/python3.10/site-packages/num2words/lang_AM.py", line 87, in to_cardinal
    words, num = self.clean(val)
TypeError: cannot unpack non-iterable NoneType object`

### Steps to reproduce

`from num2words import num2words

amount = 1210

print(num2words(amount, lang='am'))`

**Comment by jqueguiner** [comment]
For anyone landing here: this is fixed in [num2words2](https://github.com/jqueguiner/num2words2), an actively-maintained fork.

```python
>>> from num2words2 import num2words
>>> num2words(1210, lang='am')
'አንድ ሺህ ሁለት መቶ አሥር'
```

Install: `pip install num2words2`.

---
*Status update: still resolved in num2words2 **v1.0.9** (latest release on PyPI / AUR `python-num2words2`, 2026-05-01). See https://github.com/jqueguiner/num2words2/releases for the full changelog since the fork.*
